name: gitHub actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"